networks:
  experiment:
    driver: bridge

services:
  microservice:
    build: ./golang-app
    container_name: microservice
    ports:
      - "8080:8080"
    networks:
      - experiment

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: "0:0" # jalankan sebagai root
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus/data # ubah path
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'`
      - '--storage.tsdb.path=/prometheus/data' # tambahkan ini
    networks:
      - experiment

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./docker/grafana/datasources:/etc/grafana/provisioning/datasources
      - grafana_data:/var/lib/grafana # ubah ini
    networks:
      - experiment

# Tambahkan ini di level teratas file docker-compose.yml
volumes:
  prometheus_data:
  grafana_data:
