# Use the official Golang image to create a build artifact.
FROM golang:1.23.3 as builder

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy the source from the current directory to the Working Directory inside the container
COPY . .

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod tidy

# Build the Go app for Linux, since we'll run the server on linux alpine
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o microservice .

# Start a new stage from scratch
FROM alpine:latest

WORKDIR /app

# # Copy the Pre-built binary file from the previous stage
COPY --from=builder /app/microservice .

# # Expose port 1000 to the outside world
EXPOSE 8080

# Command to run the executable
ENTRYPOINT ["/app/microservice"]